---
- name: Add SSH pub key to authorized_keys
  file: path=/root/.ssh/ state=directory
- name: Copy MvnRepo to hosts
  copy:
    src: /root/.ssh/id_rsa.pub
    dest: /root/.ssh/authorized_keys

- name: SSH Key Var
  set_fact: ssh_key="{{ lookup('file', '/root/.ssh/id_rsa.pub') | regex_search('(?<=ssh-rsa([\\s]))(.*)(?=([\\s]))') }}"
- debug: msg="ssh_key={{ ssh_key }}"
- name: Add SSH pub key to Karaf
  lineinfile:
    dest=/opt/karaf/etc/keys.properties
    line="karaf={{ ssh_key }},_g_:admingroup,ssh"