---
- name: Build app
  hosts: AnsibleMaster
  roles:
    - build_app

- name: Create the DinD network infrastructure
  hosts: AnsibleMaster
  roles:
    - dind_all

- name: Generate SSH key
  hosts: AnsibleMaster
  roles:
    - generate_ssh_key

- name: Start Karafs
  hosts:
  - ServerBroker
  - ServerDemoApp
  roles:
    - deploy_ssh_keys
    - run_karaf

- name: Run JMS-Broker
  hosts: KarafBroker
  gather_facts: no
  roles:
    - deploy_broker

- name: Run DemoApp
  hosts: KarafDemoApp
  gather_facts: no
  roles:
    - deploy_app

- name: Prompt before sending DemoApp msgs
  hosts:
  - AnsibleMaster
  tasks:
  - pause:
      prompt: "Press Enter to send DemoApp msgs."

- name: Send DemoApp messages
  hosts:
  - karaf01
  gather_facts: no
  roles:
    - send_msgs

- name: Prompt that prevents Docker container shutdown
  hosts:
  - AnsibleMaster
  tasks:
  - pause:
      prompt: "Press Enter to finish the build. This stops all docker containers (and the Karaf instances running on these containers)."