---
- name: Install features-file
  raw: 'feature:repo-add mvn:ch.wengle.demoapp/karaf-features/1.0-SNAPSHOT/xml/features'
- name: Install demoApp
  raw: 'feature:install demoApp'
- name: List Bundles
  raw: "list"
  register: listOutput
- debug: msg="{{ listOutput.stdout }}"