---
- name: pwdCmd
  command: "pwd"
  register: pwdCmdOutput
- debug: msg="{{ pwdCmdOutput.stdout }}"
- name: lsCmd
  command: "ls"
  register: lsCmdOutput
- debug: msg="{{ lsCmdOutput.stdout }}"
- name: Copy MvnRepo to hosts
  copy:
    src: /root/.m2/repository
    dest: /root/.m2/